simulation:
  num_agents: 3
  tick_interval: 1.0
  reflect_threshold: 3.5
  map_width: 400
  map_height: 300
  perception_radius: 50
  agent_speed: 4.0
  minutes_per_tick: 5
llm:
  provider: together
  model: meta-llama/Llama-3.2-3B-Instruct-Turbo
  api_key: ${TOGETHER_API_KEY}
  temperature: 0.1
  max_tokens: 512
  timeout: 5.0
embedding:
  model: sentence-transformers/all-MiniLM-L6-v2
  dimension: 384
retrieval:
  default_alpha: 0.5
  default_beta: 0.3
  default_gamma: 0.2
  top_k: 10
compilation:
  use_compiled: true
  compiled_dir: ./compiled/
  optimizer: gepa
  seeds_path: ./seeds/
  gepa:
    budget: 40
  miprov2:
    auto: medium
    max_bootstrapped_demos: 4
    max_labeled_demos: 5
    num_trials: 10
  use_town_agent_gepa: true
database:
  path: data/town_v2.db
  memory_prune_days: 7
  importance_threshold: 0.2
observability:
  log_level: INFO
  log_file: logs/mini_town.log
  structured_events: logs/agent_events.jsonl
god_mode:
  enabled: true
